apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-ui-config
  namespace: jaeger  # Change namespace if needed
data:
  ui-config.json: |
    {
      "dependencies": {
        "dagMaxNumServices": 200,
        "menuEnabled": true
      },
      "monitor": {
        "menuEnabled": true
      },
      "archiveEnabled": true,
      "tracking": {
        "gaID": "UA-000000-2",
        "trackErrors": true
      },
      "menu": [
        {
          "label": "About Jaeger",
          "items": [
            {
              "label": "GitHub",
              "url": "https://github.com/jaegertracing/jaeger"
            },
            {
              "label": "Docs",
              "url": "http://jaeger.readthedocs.io/en/latest/"
            }
          ]
        }
      ],
      "search": {
        "maxLookback": {
          "label": "2 Days",
          "value": "2d"
        },
        "maxLimit": 1500
      },
      "linkPatterns": [
        {
          "type": "process",
          "key": "jaeger.version",
          "url": "https://github.com/jaegertracing/jaeger-client-java/releases/tag/#{jaeger.version}",
          "text": "Information about Jaeger release #{jaeger.version}"
        },
        {
          "type": "tags",
          "key": "uniqueId",
          "url": "https://mykibana.com/uniqueId=#{uniqueId}&traceId=#{trace.traceID}",
          "text": "Redirect to kibana to view log"
        },
        {
          "type": "traces",
          "url": "https://my-logs.server?from=#{startTime | add -60000000 | epoch_micros_to_date_iso}&to=#{endTime | add 60000000 | epoch_micros_to_date_iso}'",
          "text": "Redirect to kibana to view log with formatted dates"
        }
      ]
    }
