apiVersion: v2
appVersion: 1.21.1
dependencies:
- name: k8ssandra-common
  repository: https://helm.k8ssandra.io
  version: 0.29.0
- name: cass-operator
  repository: https://helm.k8ssandra.io
  version: 0.55.0
description: 'Kubernetes operator which handles the provisioning and management of
  K8ssandra clusters. '
home: https://github.com/k8ssandra/k8ssandra-operator
maintainers:
- email: k8ssandra-developers@googlegroups.com
  name: K8ssandra Team
  url: https://github.com/k8ssandra
name: k8ssandra-operator
sources:
- https://github.com/k8ssandra/k8ssandra-operator
- https://github.com/k8ssandra/k8ssandra/tree/main/charts/k8ssandra-operator
type: application
version: 1.21.1
